### ISSUE TITLE
ModuleNotFoundError: No module named 'gdf'

### ISSUE THREAD

**Issue by stinbuaa** [Stability-AI/StableCascade#10]
When I try to train model c using finetune_c_3b.yaml, the following error is reported. I'm sure that when I installed the required libraries in the virtual environment with the command python3 -m pip install -r requirements.txt, there was no error reported. How can I resolve this issue?

```
python3 train/train_c.py configs/training/finetune_c_3b.yaml
Traceback (most recent call last):
  File "F:\app\StableCascade\train\train_c.py", line 11, in <module>
    from gdf import GDF, EpsilonTarget, CosineSchedule
ModuleNotFoundError: No module named 'gdf'
```

**Comment by dome272** [comment]
GDF is here in the same [repo](https://github.com/Stability-AI/StableCascade/tree/master/gdf). Are you sure you are running the script from the root folder of this directory?

**Comment by idilmetin** [comment]
I'm having the same issue even though I'm running the script from the root folder. Any help is appreciated!

**Comment by jlmaoju** [comment]
same issue here

**Comment by dae-sun** [comment]
Try adding below line at train/train_c.py line 7
`import sys; sys.path.append('.')`

**Comment by heyalexchoi** [comment]
alternatively you can set PYTHONPATH in your shell environment and you don't have to change the repo files:
`export PYTHONPATH="${PYTHONPATH}:."` if you are in `StableCascade` directory.
