### ISSUE TITLE
decoder mismatch

### ISSUE THREAD

**Issue by tyokota** [Stability-AI/StableCascade#65]
Decoder mismatch tensor shape.

```ValueError: Cannot load C:\Users\tyoko\.cache\huggingface\hub\models--stabilityai--stable-cascade\snapshots\f2a84281d6f8db3c757195dd0c9a38dbdea90bb4\decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.```

**Comment by HarryPsalms** [comment]
Getting same error. Running Linux with Nvidia driver 535.154.05, cuda release 12.1.
Cloned repo, created+activated venv, ran pip -r install requirements.txt followed by gradio and diffusers per the installation notes

**Comment by BoxFishLab** [comment]
I'm having the same problem.the diffusers version is diffusers-0.27.0.dev0.

**Comment by BoxFishLab** [comment]
> I'm having the same problem.the diffusers version is diffusers-0.27.0.dev0.
in https://huggingface.co/stabilityai/stable-cascade/discussions/13
To fix the size mismatch error, replace
"c_in": 4
with
"in_channels": 4
in the decoder config.json. (Reason is this commit: https://github.com/kashif/diffusers/commit/cbd07758adc1848f3a9eb115f9467e43f8560726)

**Comment by BoxFishLab** [comment]
> Getting same error. Running Linux with Nvidia driver 535.154.05, cuda release 12.1. Cloned repo, created+activated venv, ran pip -r install requirements.txt followed by gradio and diffusers per the installation notes

try this

**Comment by todor943** [comment]
I also have this problem on Windows 11

**Comment by songproducer** [comment]
Where is the decoder config.json file please?

**Comment by kime541200** [comment]
I encounter the same problem in Windows11, is there any solution?

**Comment by kime541200** [comment]
> I encounter the same problem in Windows11, is there any solution?

This work for me --> [#58](https://github.com/Stability-AI/StableCascade/issues/58#issuecomment-1949882396)

**Comment by todor943** [comment]
"Not Found"
