### ISSUE TITLE
It seems that the stageA codebook was not used during inference?

### ISSUE THREAD

**Issue by laolongboy** [Stability-AI/StableCascade#68]
<img width="1056" alt="image" src="https://github.com/Stability-AI/StableCascade/assets/25175047/b0bfadcc-ad9a-4c82-bcda-96f6ade069da">

**Comment by dome272** [comment]
Hey this is for an old version of the model. Stage B is a diffusion and Stage A is used as a VAE. Also the 16 x 24 x 24 are not flattened anymore, they are interpolated and concatenated to the Stage B input. Does that help?

**Comment by laolongboy** [comment]
> Hey this is for an old version of the model. Stage B is a diffusion and Stage A is used as a VAE. Also the 16 x 24 x 24 are not flattened anymore, they are interpolated and concatenated to the Stage B input. Does that help?嘿，这是旧版本的模型。 B 级是扩散，A 级用作 VAE。此外，16 x 24 x 24 不再展平，它们被插值并连接到 Stage B 输入。这有帮助吗？关闭

Got that!
