### ISSUE TITLE
Trying to finetune stage C model but keep getting "AttributeError: Can't pickle local object 'DataCore.setup_data.<locals>.<lambda>'"

### ISSUE THREAD

**Issue by peterwuuuu** [Stability-AI/StableCascade#69]
Here's my config file content:
```
# GLOBAL STUFF
experiment_id: stage_c_3b_finetuning
checkpoint_path: output
output_path: output
model_version: 3.6B

# WandB
wandb_project: StableCascade
wandb_entity: wandb_username

# TRAINING PARAMS
lr: 1.0e-4
batch_size: 1
image_size: 1024
multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 1
updates: 10000
backup_every: 20000
save_every: 2000
warmup_updates: 1
use_fsdp: False

# GDF
adaptive_loss_weight: True

# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path: file:/data/gameIcon.tar
effnet_checkpoint_path: models/effnet_encoder.safetensors
previewer_checkpoint_path: models/previewer.safetensors
generator_checkpoint_path: models/stage_c_bf16.safetensors
```

And I did some modification on train_c.py under `import os`, which is this line ```sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))``` 
otherwise it won't be able to import gdf

and I also added  
```   warpcore(single_gpu=True)```
 to the end of the train_c.py file to avoid this error from command line
```
(venv) D:\pycharmProject\StableCascade>python train/train_c.py configs/training/finetune_c_3b.yaml
Launching Script
['experiment_id', 'checkpoint_path', 'output_path', 'image_size', 'webdataset_path', 'grad_accum_steps', 'batch_size', 'updates', 'backup_every', 'save_every', 'lr', 'warmup_updates', 'model_version', 'effnet_checkpoint_path', 'previewer_checkpoint_path']
Traceback (most recent call last):
  File "D:\pycharmProject\StableCascade\train\train_c.py", line 270, in <module>
    warpcore()
  File "D:\pycharmProject\StableCascade\core\__init__.py", line 292, in __call__
    self.setup_ddp(self.config.experiment_id, single_gpu=single_gpu)  # this will change the device to the CUDA rank
  File "D:\pycharmProject\StableCascade\core\__init__.py", line 159, in setup_ddp
    init_process_group(
  File "D:\pycharmProject\StableCascade\venv\lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "D:\pycharmProject\StableCascade\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "D:\pycharmProject\StableCascade\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
```

However, after made these modifications, I made it to this step:
```
(venv) D:\pycharmProject\StableCascade>python train/train_c.py configs/training/finetune_c_3b.yaml
Launching Script
['experiment_id', 'checkpoint_path', 'output_path', 'image_size', 'webdataset_path', 'grad_accum_steps', 'batch_size', 'updates', 'backup_every', 'save_every', 'lr', 'warmup_updates', 'model_version', 'effnet_checkpoint_path', 'previewer_checkpoint_path']
Running in single thread, DDP not enabled.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:
```

But when I enter 3, then I get the error I wrote on the title
```
(venv) D:\pycharmProject\StableCascade>python train/train_c.py configs/training/finetune_c_3b.yaml
Launching Script
['experiment_id', 'checkpoint_path', 'output_path', 'image_size', 'webdataset_path', 'grad_accum_steps', 'batch_size', 'updates', 'backup_every', 'save_every', 'lr', 'warmup_updates', 'model_version', 'effnet_checkpoint_path', 'previewer_checkpoint_path']
Running in single thread, DDP not enabled.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose "Don't visualize my results"
wandb: WARNING `resume` will be ignored since W&B syncing is set to `offline`. Starting a new run with run id 1pntmpxj.
wandb: Tracking run with wandb version 0.16.3
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.

**STARTIG JOB WITH CONFIG:**
adaptive_loss_weight: true
allow_tf32: true
backup_every: 20000
batch_size: 1
bucketeer_random_ratio: 0.05
captions_getter: null
checkpoint_extension: safetensors
checkpoint_path: output
clip_image_model_name: openai/clip-vit-large-patch14
clip_text_model_name: laion/CLIP-ViT-bigG-14-laion2B-39B-b160k
dataset_filters: null
dist_file_subfolder: ''
dtype: null
effnet_checkpoint_path: models/effnet_encoder.safetensors
ema_beta: null
ema_iters: null
ema_start_iters: null
experiment_id: stage_c_3b_finetuning
generator_checkpoint_path: models/stage_c_bf16.safetensors
grad_accum_steps: 1
image_size: 1024
lr: 0.0001
model_version: 3.6B
multi_aspect_ratio:
- 1/1
- 1/2
- 1/3
- 2/3
- 3/4
- 1/5
- 2/5
- 3/5
- 4/5
- 1/6
- 5/6
- 9/16
output_path: output
previewer_checkpoint_path: models/previewer.safetensors
save_every: 2000
training: true
updates: 10000
use_fsdp: false
wandb_entity: wandb_username
wandb_project: StableCascade
warmup_updates: 1
webdataset_path: file:/data/gameIcon.tar

------------------------------------

**INFO:**
adaptive_loss: null
ema_loss: null
iter: 0
total_steps: 0
wandb_run_id: 1pntmpxj

------------------------------------

['transforms', 'clip_preprocess', 'gdf', 'sampling_configs', 'effnet_preprocess']
Training with batch size 1 (1/GPU)
Traceback (most recent call last):
  File "D:\pycharmProject\StableCascade\train\train_c.py", line 270, in <module>
    warpcore(single_gpu=True)
  File "D:\pycharmProject\StableCascade\core\__init__.py", line 313, in __call__
    data = self.setup_data(extras)
  File "D:\pycharmProject\StableCascade\train\base.py", line 127, in setup_data
    dataloader_iterator = Bucketeer(dataloader, density=self.config.image_size ** 2, factor=32,
  File "D:\pycharmProject\StableCascade\core\data\bucketeer.py", line 18, in __init__
    self.iterator = iter(dataloader)
  File "D:\pycharmProject\StableCascade\venv\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "D:\pycharmProject\StableCascade\venv\lib\site-packages\torch\utils\data\dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\pycharmProject\StableCascade\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1039, in __init__
    w.start()
  File "C:\Apps\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Apps\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Apps\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Apps\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Apps\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'DataCore.setup_data.<locals>.<lambda>'
wandb: You can sync this run to the cloud by running:
wandb: wandb sync D:\pycharmProject\StableCascade\wandb\offline-run-20240218_205509-1pntmpxj
wandb: Find logs at: .\wandb\offline-run-20240218_205509-1pntmpxj\logs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Apps\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Apps\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

Can anyone help me with this? It will be greatly helpful.

**Comment by HackTales** [comment]
I have the same issue on Windows and I had to twist the code a bit to make it work.
It seems that torch pickle loader on Windows does not support lambdas while resolving the dataset, so I had to replace every lambda used in `train/base.py` with class methods.

This code just works - it starts the lora training - dunno if it will complete successfully (just started) 

Replace `webdataset_preprocessors` and  `setup_data` inside the file with:

```python
    def base_identity(self,x):
        if isinstance(x, bytes):
            x = x.decode('utf-8')
        return x

    def webdataset_preprocessors(self, extras: Extras):
       

        # CUSTOM CAPTIONS GETTER -----
        def get_caption(oc, c, p_og=0.05):  # cog_contexual, cog_caption
            if p_og > 0 and np.random.rand() < p_og and len(oc) > 0:
                return self.base_identity(oc)
            else:
                return self.base_identity(c)

        captions_getter = MultiGetter(rules={
            ('old_caption', 'caption'): lambda oc, c: get_caption(json.loads(oc)['og_caption'], c, p_og=0.05)
        })

        return [
            ('jpg;png',
             torchvision.transforms.ToTensor() if self.config.multi_aspect_ratio is not None else extras.transforms,
             'images'),
            ('txt', self.base_identity, 'captions') if self.config.captions_getter is None else (
                self.config.captions_getter[0], eval(self.config.captions_getter[1]), 'captions'),
        ]

    def wds_identity(self, x):
        return x
    def map_preprocessor(self, x):
        result = {}
        items = self.wa_preprocessor
        for i, p in enumerate(items):
            result[p[2]] = x[i]
        return result

    def setup_data(self, extras: Extras) -> WarpCore.Data:
        # SETUP DATASET
        dataset_path = self.webdataset_path()
        preprocessors = self.webdataset_preprocessors(extras)
        self.wa_preprocessor = preprocessors
        handler = warn_and_continue
        dataset = wds.WebDataset(
            dataset_path, resampled=True, handler=handler
        ).shuffle(690, handler=handler).decode(
            "pilrgb", handler=handler
        ).to_tuple(
            *[p[0] for p in preprocessors], handler=handler
        ).map_tuple(
            *[p[1] for p in preprocessors], handler=handler
        ).map(self.map_preprocessor)
#.select(
            #MultiFilter(rules={
            #    f[0]: eval(f[1]) for f in self.config.dataset_filters
            #}) if self.config.dataset_filters is not None else lambda _: True
        #)
        # SETUP DATALOADER
        real_batch_size = self.config.batch_size // (self.world_size * self.config.grad_accum_steps)
        dataloader = DataLoader(
            dataset, batch_size=real_batch_size, num_workers=8, pin_memory=True,
            collate_fn=self.wds_identity if self.config.multi_aspect_ratio is not None else None
        )
        if self.is_main_node:
            print(f"Training with batch size {self.config.batch_size} ({real_batch_size}/GPU)")

        if self.config.multi_aspect_ratio is not None:
            aspect_ratios = [float(Fraction(f)) for f in self.config.multi_aspect_ratio]
            dataloader_iterator = Bucketeer(dataloader, density=self.config.image_size ** 2, factor=32,
                                            ratios=aspect_ratios, p_random_ratio=self.config.bucketeer_random_ratio,
                                            interpolate_nearest=False)  # , use_smartcrop=True)
        else:
            dataloader_iterator = iter(dataloader)

        return self.Data(dataset=dataset, dataloader=dataloader, iterator=dataloader_iterator)
```
Also because the training is spawning itself to load the dataset (I think) without arguments some assertion relative to config will fail, so I have to comment those lines on file `core/utils/base_dto.py` (i think it will break things if you do not configure properly your training yaml).

```python
        #assert (
        #    len(missing_kwargs) == 0
        #), f"Required fields missing initializing this DTO: {missing_kwargs}."`
```

 I supect there are more elegant ways to solve this.

**Comment by peterwuuuu** [comment]
> I have the same issue on Windows and I had to twist the code a bit to make it work. It seems that torch pickle loader on Windows does not support lambdas while resolving the dataset, so I had to replace every lambda used in `train/base.py` with class methods.
> 
> This code just works - it starts the lora training - dunno if it will complete successfully (just started)
> 
> Replace `webdataset_preprocessors` and `setup_data` inside the file with:
> 
> ```python
>     def base_identity(self,x):
>         if isinstance(x, bytes):
>             x = x.decode('utf-8')
>         return x
> 
>     def webdataset_preprocessors(self, extras: Extras):
>        
> 
>         # CUSTOM CAPTIONS GETTER -----
>         def get_caption(oc, c, p_og=0.05):  # cog_contexual, cog_caption
>             if p_og > 0 and np.random.rand() < p_og and len(oc) > 0:
>                 return self.base_identity(oc)
>             else:
>                 return self.base_identity(c)
> 
>         captions_getter = MultiGetter(rules={
>             ('old_caption', 'caption'): lambda oc, c: get_caption(json.loads(oc)['og_caption'], c, p_og=0.05)
>         })
> 
>         return [
>             ('jpg;png',
>              torchvision.transforms.ToTensor() if self.config.multi_aspect_ratio is not None else extras.transforms,
>              'images'),
>             ('txt', self.base_identity, 'captions') if self.config.captions_getter is None else (
>                 self.config.captions_getter[0], eval(self.config.captions_getter[1]), 'captions'),
>         ]
> 
>     def wds_identity(self, x):
>         return x
>     def map_preprocessor(self, x):
>         result = {}
>         items = self.wa_preprocessor
>         for i, p in enumerate(items):
>             result[p[2]] = x[i]
>         return result
> 
>     def setup_data(self, extras: Extras) -> WarpCore.Data:
>         # SETUP DATASET
>         dataset_path = self.webdataset_path()
>         preprocessors = self.webdataset_preprocessors(extras)
>         self.wa_preprocessor = preprocessors
>         handler = warn_and_continue
>         dataset = wds.WebDataset(
>             dataset_path, resampled=True, handler=handler
>         ).shuffle(690, handler=handler).decode(
>             "pilrgb", handler=handler
>         ).to_tuple(
>             *[p[0] for p in preprocessors], handler=handler
>         ).map_tuple(
>             *[p[1] for p in preprocessors], handler=handler
>         ).map(self.map_preprocessor)
> #.select(
>             #MultiFilter(rules={
>             #    f[0]: eval(f[1]) for f in self.config.dataset_filters
>             #}) if self.config.dataset_filters is not None else lambda _: True
>         #)
>         # SETUP DATALOADER
>         real_batch_size = self.config.batch_size // (self.world_size * self.config.grad_accum_steps)
>         dataloader = DataLoader(
>             dataset, batch_size=real_batch_size, num_workers=8, pin_memory=True,
>             collate_fn=self.wds_identity if self.config.multi_aspect_ratio is not None else None
>         )
>         if self.is_main_node:
>             print(f"Training with batch size {self.config.batch_size} ({real_batch_size}/GPU)")
> 
>         if self.config.multi_aspect_ratio is not None:
>             aspect_ratios = [float(Fraction(f)) for f in self.config.multi_aspect_ratio]
>             dataloader_iterator = Bucketeer(dataloader, density=self.config.image_size ** 2, factor=32,
>                                             ratios=aspect_ratios, p_random_ratio=self.config.bucketeer_random_ratio,
>                                             interpolate_nearest=False)  # , use_smartcrop=True)
>         else:
>             dataloader_iterator = iter(dataloader)
> 
>         return self.Data(dataset=dataset, dataloader=dataloader, iterator=dataloader_iterator)
> ```
> 
> Also because the training is spawning itself to load the dataset (I think) without arguments some assertion relative to config will fail, so I have to comment those lines on file `core/utils/base_dto.py` (i think it will break things if you do not configure properly your training yaml).
> 
> ```python
>         #assert (
>         #    len(missing_kwargs) == 0
>         #), f"Required fields missing initializing this DTO: {missing_kwargs}."`
> ```
> 
> I supect there are more elegant ways to solve this.

Thx mate! So I guess it will work for train_c.py as well? I'll test it out later. 

Btw could you also let me know if the training complete successfully or not?

**Comment by HackTales** [comment]
I forget to mention that i use it for training lora and not finetuning but from the readme it seems to be very similar as it trains the c model.
However it completes the training successfully on the 1B model and the fernando dog dataset. (less than 2h on RTX 4090, 10k steps * 4).

Here the image of `cinematic photo of a dog [fernando] wearing a space suit` with the trained lora (B on 16bf big, C on lite full precision)

![image](https://github.com/Stability-AI/StableCascade/assets/62334184/d4281b96-2de9-4a70-8021-7db91ab44adc)

**Comment by peterwuuuu** [comment]
> I forget to mention that i use it for training lora and not finetuning but from the readme it seems to be very similar as it trains the c model. However it completes the training successfully on the 1B model and the fernando dog dataset. (less than 2h on RTX 4090, 10k steps * 4).
> 
> Here the image of `cinematic photo of a dog [fernando] wearing a space suit` with the trained lora (B on 16bf big, C on lite full precision)
> 
> ![image](https://private-user-images.githubusercontent.com/62334184/305728497-d4281b96-2de9-4a70-8021-7db91ab44adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzQyMTIsIm5iZiI6MTcwODMzMzkxMiwicGF0aCI6Ii82MjMzNDE4NC8zMDU3Mjg0OTctZDQyODFiOTYtMmRlOS00YTcwLTgwMjEtN2RiOTFhYjQ0YWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA5MTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZTI3NmYyNDVhN2Y1NGI2NTI3NWFhMzk2ZTFlMTg5ZDE1YWFmNDY2YjlkMzYwNmEyMzJmOTRhYTZmYzUzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L0hVDWmC3_8QbC1jbVEwa4QdPr9zHajuZh5vvC5tLJw)

Finally, I managed to start and complete the training. Initially, I tried finetuning the 3B stage C model, but the training stopped because it ran out of VRAM. Then, I attempted to finetune the 1B stage C model, which successfully completed the training after using your modified base.py code in place of the original. However, I made additional modifications:

1.  Commented out the   line 313  ```barrier()``` from base.py  by follow the solution from this issue #28 
2.  In command line ```set SLURM_LOCALID=0```   by follow the solution from this  issue #17  

This sums up the major changes I made. However, since I only trained with 50 images and 2000 steps, the results were not optimal, which was expected. My GPU is an RTX 3090; it took approximately 2 hours and 20 minutes to complete the training, nearly consumed all of the VRAM (almost 24GB).

**Comment by peterwuuuu** [comment]
@HackTales 
Hey man, I'm also trying to train a lora using stable cascade, but I'm not really sure where to use this lora, did you put the loras to stable diffusion webui/comfyui's model/lora folder? or did you used the inference notebook provided by stable cascade repo? 

Do you mind share your lora training config yaml(I assume finetune_c_1b?) and inference notebook(if you did it this way)?

Thanks in advance.

**Comment by HackTales** [comment]
> @HackTales Hey man, I'm also trying to train a lora using stable cascade, but I'm not really sure where to use this lora, did you put the loras to stable diffusion webui/comfyui's model/lora folder? or did you used the inference notebook provided by stable cascade repo?
> 
> Do you mind share your lora training config yaml(I assume finetune_c_1b?) and inference notebook(if you did it this way)?
> 
> Thanks in advance.

I just use the jupyter notebook available here https://github.com/Stability-AI/StableCascade/blob/master/inference/lora.ipynb and changing the yaml to match the created lora.

I have to try comfyui, but I think it is totally possible.

I'm unable to share the yaml rn, but I can do it later (it isn't very unchanged from the default except from training data path).

I trained a lora with different photo of a woman on 1B but the results aren't very good after 10k (~0.27 loss, lr=0.0001) and 80k (~0.18 loss, , lr=0.0001 till 20k, lr=0.00001 after 20k): "woman" or "girl" token  is overfitted with the training subject, even "boy" sometimes. Image size was set to 768 with different ratios.

The subject is definitely present, but quality of faces isn't good. 

I think we need some kind of regulation.

Also, I noted that from the preview of every 100 steps, sometimes the first 2/3 images are randomly cut, and the subject is not present. I think this is a random input used as training sample, and this can be an issue too because it can contaminate the training data with noise. Speculation: resize images manually and  play with ratios settings can improve the result. Maybe the same issue  https://github.com/Stability-AI/StableCascade/issues/66

Right now I am training at 1024 instead of 768 to see if the results are better and not overfitted (with the default ratios and same images).

Unable to train with batch_size < 4 (throws error).

**Comment by peterwuuuu** [comment]
> > @HackTales Hey man, I'm also trying to train a lora using stable cascade, but I'm not really sure where to use this lora, did you put the loras to stable diffusion webui/comfyui's model/lora folder? or did you used the inference notebook provided by stable cascade repo?
> > Do you mind share your lora training config yaml(I assume finetune_c_1b?) and inference notebook(if you did it this way)?
> > Thanks in advance.
> 
> I just use the jupyter notebook available here https://github.com/Stability-AI/StableCascade/blob/master/inference/lora.ipynb and changing the yaml to match the created lora.
> 
> I have to try comfyui, but I think it is totally possible.
> 
> I'm unable to share the yaml rn, but I can do it later (it isn't very unchanged from the default except from training data path).
> 
> I trained a lora with different photo of a woman on 1B but the results aren't very good after 10k (~0.27 loss, lr=0.0001) and 80k (~0.18 loss, , lr=0.0001 till 20k, lr=0.00001 after 20k): "woman" or "girl" token is overfitted with the training subject, even "boy" sometimes. Image size was set to 768 with different ratios.
> 
> The subject is definitely present, but quality of faces isn't good.
> 
> I think we need some kind of regulation.
> 
> Also, I noted that from the preview of every 100 steps, sometimes the first 2/3 images are randomly cut, and the subject is not present. I think this is a random input used as training sample, and this can be an issue too because it can contaminate the training data with noise. Speculation: resize images manually and play with ratios settings can improve the result. Maybe the same issue #66
> 
> Right now I am training at 1024 instead of 768 to see if the results are better and not overfitted (with the default ratios and same images).
> 
> Unable to train with batch_size < 4 (throws error).

Thanks man, really appreciate. And yes the randomly cutted previews can be an issue. 

I will definitely try different ratios for lora trainings.

**Comment by apluka34** [comment]
@peterwuuuu Hi, can you share your config file for lora training and how you set up the dataset? I have tried to train several times  but the results are not relevant .-.

**Comment by peterwuuuu** [comment]
@quocanh34 

Sure, here's my config
```
# GLOBAL STUFF
experiment_id: stage_c_1b_lora
checkpoint_path: output
output_path: output
model_version: 1B

# WandB
wandb_project: StableCascade
wandb_entity: wandb_username

# TRAINING PARAMS
lr: 1.0e-4
batch_size: 1
image_size: 768
multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 1
updates: 3000
backup_every: 1500
save_every: 600
warmup_updates: 1
# use_fsdp: True -> FSDP doesn't work at the moment for LoRA
use_fsdp: False

# GDF
# adaptive_loss_weight: True

# LoRA specific
module_filters: ['.attn']
rank: 128
train_tokens:
  # - ['^snail', null] # token starts with "snail" -> "snail" & "snails", don't need to be reinitialized
  - ['[game icon]', '^icon</w>'] # custom token [snail], initialize as avg of snail & snails


# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path: file:D:/pycharmProject/StableCascade/data/gameIcon30768.tar
effnet_checkpoint_path: models/effnet_encoder.safetensors
previewer_checkpoint_path: models/previewer.safetensors
generator_checkpoint_path: models/stage_c_lite.safetensors
```

Then the dataset I just did what I usually do for normal lora training using kohya's tool. Basically 30 imgs with 30 txt tagging files, and the names are the same for each pair of jpg/png and txt files. But just be careful to compress the folder that store the img and txt files into .tar format(not rar format cuz I made this silly mistake :-) ).

But the results turned out not good. I can see that it somehow absorbed the painting style a little bit, but the overall quality and details are not desireable.
