### ISSUE TITLE
Clean new comfy install but  checkpoint loading error help pls

### ISSUE THREAD

**Issue by zappazack** [Stability-AI/StableCascade#96]
error occurred when executing CheckpointLoaderSimple:

'model.diffusion_model.input_blocks.0.0.weight'

File "C:\Users\Intersurf\Documents\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Intersurf\Documents\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Intersurf\Documents\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Intersurf\Documents\ComfyUI\nodes.py", line 540, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Intersurf\Documents\ComfyUI\comfy\sd.py", line 500, in load_checkpoint_guess_config
model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Intersurf\Documents\ComfyUI\comfy\model_detection.py", line 191, in model_config_from_unet
unet_config = detect_unet_config(state_dict, unet_key_prefix)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Intersurf\Documents\ComfyUI\comfy\model_detection.py", line 77, in detect_unet_config
model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by FurkanGozukara** [comment]
ye it is hard to run

for who cant make we have amazing app : https://github.com/Stability-AI/StableCascade/issues/125

**Comment by HanboyLee** [comment]
@zappazack Has your problem been resolved? I have encountered the same issue.

**Comment by zappazack** [comment]
> error occurred when executing CheckpointLoaderSimple:
> 
> 'model.diffusion_model.input_blocks.0.0

Yes U need a clean comfy installation and the cascade checkpoints for comfy. They are different than the as standard released chpoints. It works.

**Comment by zappazack** [comment]
> @zappazack Has your problem been resolved? I have encountered the same issue.

https://huggingface.co/stabilityai/stable-cascade/commit/e3aee2fd11a00865f5c085d3e741f2e51aef12d3
They are named as comfyui checkpoints/stable cascade..
